environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"

max_jobs: 4
clone_depth: 1
branches:
  only:
  - master

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

platform:
  - x86
  - x64

matrix:
  fast_finish: true

build: off

test_script:
  - node --version
  - npm --version
  - npm test
